[build]
  command = "remix build"
  publish = "public"

[dev]
  command = "remix watch"
  port = 3000

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200

[[redirects]]
  from = "/admin"
  to = "https://api.fayardthibault.fr/admin"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

[[headers]]
  for = "/build/*"
  [headers.values]
    "Cache-Control" = "public, max-age=31536000, s-maxage=31536000"
